---
#
# LLDAP - Light LDAP Implementation
#
services:

  lldap:
    image: nitnelave/lldap:stable
    container_name: ${LLDAP_CONTAINER_NAME:-lldap}
    volumes:
      - ${APPDATA_DIR}/lldap:/data
    ports:
      - "3890:3890"
    networks:
      - traefik
    labels:
      net.unraid.docker.icon: ${MY_ICONS_URL}/ldap.png
      net.unraid.docker.managed: composeman
      net.unraid.docker.shell: bash
      net.unraid.docker.webui: https://${LLDAP_HOSTNAME:-lldap}.${DOMAIN_NAME}
      traefik.enable: "true"
      traefik.http.routers.lldap.entrypoints: https
      traefik.http.routers.lldap.middlewares: auth-chain@file
      traefik.http.routers.lldap.rule: Host(`${LLDAP_HOSTNAME:-lldap}.${DOMAIN_NAME}`)
      traefik.http.routers.lldap.service: lldap
      traefik.http.services.lldap.loadbalancer.server.port: 17170
    environment:
      UID: ${PUID}
      GID: ${PGID}
      TZ: ${TZ}
      LLDAP_JWT_SECRET_FILE: /run/secrets/lldap_jwt_secret
      LLDAP_LDAP_BASE_DN: ${LLDAP_LDAP_BASE_DN}
      LLDAP_LDAP_USER_PASS_FILE: /run/secrets/lldap_user_password
    secrets:
      - lldap_jwt_secret
      - lldap_user_password
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  traefik:
    external: true

secrets:
  lldap_jwt_secret:
    file: ${SECRETS_DIR}/lldap_jwt_secret
  lldap_user_password:
    file: ${SECRETS_DIR}/lldap_user_password
