---
#
# Authelia - Single sign-on and two-factor authentication
#
services:

  authelia:
    image: authelia/authelia:latest
    container_name: ${AUTHELIA_CONTAINER_NAME:-authelia}
    volumes:
      - ${APPDATA_DIR}/authelia:/config
      - ./configuration.yml:/config/configuration.yml
    ports:
      - "${AUTHELIA_PORT:-9091}:9091"
    networks:
      - mail_relay
      - traefik
    labels:
      net.unraid.docker.icon: ${DASHBOARD_ICONS_URL}/authelia.png
      net.unraid.docker.managed: composeman
      net.unraid.docker.shell: sh
      net.unraid.docker.webui: https://${AUTHELIA_HOSTNAME:-auth}.${DOMAIN_NAME}
      traefik.enable: "true"
      traefik.http.routers.authelia.entrypoints: https
      traefik.http.routers.authelia.middlewares: auth-chain@file
      traefik.http.routers.authelia.rule: Host(`${AUTHELIA_HOSTNAME:-auth}.${DOMAIN_NAME}`)
      traefik.http.routers.authelia.service: authelia
      traefik.http.services.authelia.loadbalancer.server.port: 9091
    environment:
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /run/secrets/lldap_admin_password
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /run/secrets/authelia_oidc_hmac_secret
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE: /run/secrets/authelia_oidc_private_key
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/authelia_jwt_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia_storage_encryption_key
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    secrets:
      - authelia_jwt_secret
      - authelia_oidc_hmac_secret
      - authelia_oidc_private_key
      - authelia_storage_encryption_key
      - lldap_admin_password
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  mail_relay:
    external: true
  traefik:
    external: true

secrets:
  authelia_jwt_secret:
    file: ${SECRETS_DIR}/authelia_jwt_secret
  authelia_oidc_hmac_secret:
    file: ${SECRETS_DIR}/authelia_oidc_hmac_secret
  authelia_oidc_private_key:
    file: ${SECRETS_DIR}/authelia_oidc_private_key
  authelia_storage_encryption_key:
    file: ${SECRETS_DIR}/authelia_storage_encryption_key
  lldap_admin_password:
    file: ${SECRETS_DIR}/lldap_admin_password
