#
# Authelia - Single sign-on and two-factor authentication
#
services:

  authelia:
    image: authelia/authelia:latest
    container_name: ${AUTHELIA_CONTAINER_NAME:-authelia}
    volumes:
      - ${APPDATA_DIR}/authelia:/config
      - ./configuration.yml:/config/configuration.yml
    ports:
      - "${AUTHELIA_PORT:-9091}:9091"
    networks:
      - mail_relay
      - openldap
      - traefik
    labels:
      net.unraid.docker.icon: ${DASHBOARD_ICONS_URL}/authelia.png
      net.unraid.docker.managed: composeman
      net.unraid.docker.shell: shell
      net.unraid.docker.webui: https://${LLDAP_HOSTNAME:-lldap}.${DOMAIN_NAME}
      traefik.enable: "true"
      traefik.http.routers.authelia.entrypoints: https
      traefik.http.routers.authelia.middlewares: no-auth-chain@file
      traefik.http.routers.authelia.rule: Host(`${AUTHELIA_HOSTNAME:-auth}.${DOMAIN_NAME}`)
      traefik.http.routers.authelia.service: authelia
      traefik.http.services.authelia.loadbalancer.server.port: 9091
    environment:
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /run/secrets/openldap_admin_password
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/authelia_jwt_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia_storage_encryption_key
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    secrets:
      - authelia_jwt_secret
      - authelia_storage_encryption_key
      - openldap_admin_password
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  mail_relay:
    external: true
  openldap:
    external: true
  traefik:
    external: true

secrets:
  authelia_jwt_secret:
    file: ${SECRETS_DIR}/authelia_jwt_secret
  authelia_storage_encryption_key:
    file: ${SECRETS_DIR}/authelia_storage_encryption_key
  openldap_admin_password:
    file: ${SECRETS_DIR}/openldap_admin_password
