#
# Scrutiny collector - Collector for S.M.A.R.T. monitoring
#
services:

  scrutiny-collector:
    image: ghcr.io/analogj/scrutiny:master-collector
    container_name: ${SCRUTINY_COLLECTOR_CONTAINER_NAME:-scrutiny-collector}
    volumes:
      - /run/udev:/run/udev:ro
    devices:
      - /dev/disk/by-id/ata-Samsung_SSD_860_EVO_500GB_S3Z1NB0KB95701R
      - /dev/disk/by-id/ata-Samsung_SSD_860_EVO_500GB_S3Z1NB0KB95686W
      - /dev/disk/by-id/ata-WDC_WD140EDGZ-11B1PA0_9MJ2UXRT
      - /dev/disk/by-id/ata-WDC_WD140EDGZ-11B1PA0_9MJ2YUAU
    networks:
      - internal
    labels:
      net.unraid.docker.icon: ${DASHBOARD_ICONS_URL}/scrutiny.png
      net.unraid.docker.managed: composeman
      net.unraid.docker.shell: bash
    environment:
      COLLECTOR_API_ENDPOINT: ${SCRUTINY_API_ENDPOINT}
      COLLECTOR_HOST_ID: ${SERVER_NAME}
      TZ: ${TZ}
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO

networks:
  internal: