---
#
# Nextcloud - Content collaboration platform
#
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    init: true
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8083:8080"
    networks:
      - nextcloud-aio
    labels:
      net.unraid.docker.icon: ${DASHBOARD_ICONS_URL}/nextcloud.png
      net.unraid.docker.managed: composeman
      net.unraid.docker.shell: bash
      net.unraid.docker.webui: https://192.168.121.2:8083
    environment:
      APACHE_PORT: "11000"
      APACHE_IP_BINDING: "0.0.0.0"
      NEXTCLOUD_DATADIR: ${NEXTCLOUD_DIR}/data
      NEXTCLOUD_ENABLE_DRI_DEVICE: "true"
    restart: always

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  nextcloud-aio:
    name: nextcloud-aio
