---
#
# Scrutiny - Web UI for S.M.A.R.T. monitoring
#
services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: ${SCRUTINY_CONTAINER_NAME:-scrutiny}
    volumes:
      - ${APPDATA_DIR}/scrutiny/config:/opt/scrutiny/config
      - ${APPDATA_DIR}/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev/disk/by-id/ata-Samsung_SSD_860_EVO_500GB_S59UNMFN804153R
      - /dev/disk/by-id/ata-WDC_WD80EDBZ-11B0ZA0_VRGJ5PSK
      - /dev/disk/by-id/ata-WDC_WD80EMZZ-11B4FB0_WD-CA03PHHG
      - /dev/disk/by-id/ata-WDC_WD80EMZZ-11B4FB0_WD-CA036WZG
      - /dev/disk/by-id/nvme-WDS500G3X0C-00SJG0_20408A804512
    ports:
      - "${SCRUTINY_PORT:-8080}:8080"
    networks:
      - traefik
    labels:
      net.unraid.docker.icon: ${DASHBOARD_ICONS_URL}/scrutiny.png
      net.unraid.docker.managed: composeman
      net.unraid.docker.shell: bash
      net.unraid.docker.webui: https://${SCRUTINY_HOSTNAME:-scrutiny}.${DOMAIN_NAME}
      traefik.enable: "true"
      traefik.http.routers.scrutiny.entrypoints: https
      traefik.http.routers.scrutiny.middlewares: auth-chain@file
      traefik.http.routers.scrutiny.rule: Host(`${SCRUTINY_HOSTNAME:-scrutiny}.${DOMAIN_NAME}`)
      traefik.http.routers.scrutiny.service: scrutiny
      traefik.http.services.scrutiny.loadbalancer.server.port: 8080
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN

networks:
  traefik:
    external: true
