---
http:
  routers:
    nas01:
      entryPoints:
        - https
      middlewares:
        - auth-chain
      service: nas01
      rule: HostRegexp(`nas01.{{env "DOMAIN_NAME"}}`)
    nas02:
      entryPoints:
        - https
      middlewares:
        - auth-chain
      service: nas02
      rule: Host(`nas02.{{env "DOMAIN_NAME"}}`)
    octoprint:
      entryPoints:
        - https
      middlewares:
        - auth-chain
      service: octoprint
      rule: HostRegexp(`octoprint.{{env "DOMAIN_NAME"}}`)
    router:
      entryPoints:
        - https
      middlewares:
        - auth-chain
      service: router
      rule: HostRegexp(`router.{{env "DOMAIN_NAME"}}`)
    pcp:
      entryPoints:
        - https
      middlewares:
        - auth-chain
      service: pcp
      rule: HostRegexp(`pcp.{{env "DOMAIN_NAME"}}`)
    router02:
      entryPoints:
        - https
      middlewares:
        - auth-chain
      service: router02
      rule: Host(`router02.{{env "DOMAIN_NAME"}}`)
    lms02:
      entryPoints:
        - https
      middlewares:
        - auth-chain
      service: lms02
      rule: Host(`lms02.{{env "DOMAIN_NAME"}}`)
    voip:
      entryPoints:
        - https
      middlewares:
        - auth-chain
      service: voip
      rule: Host(`voip.{{env "DOMAIN_NAME"}}`)

  services:
    nas01:
      loadBalancer:
        servers:
          - url: http://192.168.121.2:8080
    nas02:
      loadBalancer:
        servers:
          - url: http://192.168.40.11:8080
    octoprint:
      loadBalancer:
        servers:
          - url: http://192.168.121.9:80
    router:
      loadBalancer:
        servers:
          - url: http://192.168.121.1:80
    pcp:
      loadBalancer:
        servers:
          - url: http://192.168.121.8:80
    router02:
      loadBalancer:
        servers:
          - url: http://192.168.40.1:80
    lms02:
      loadBalancer:
        servers:
          - url: http://192.168.40.11:9000
    voip:
      loadBalancer:
        servers:
          - url: http://192.168.40.6:80
