---
#
# FreshRSS - RSS feeds aggregator
#
services:

  freshrss:
    image: lscr.io/linuxserver/freshrss
    container_name: ${FRESHRSS_CONTAINER_NAME:-freshrss}
    volumes:
      - ${APPDATA_DIR}/freshrss:/config
    networks:
      - traefik
    labels:
      net.unraid.docker.icon: ${DASHBOARD_ICONS_URL}/freshrss.png
      net.unraid.docker.managed: composeman
      net.unraid.docker.shell: bash
      net.unraid.docker.webui: https://${FRESHRSS_HOSTNAME:-freshrss}.${DOMAIN_NAME}
      traefik.enable: "true"
      traefik.http.routers.freshrss.entrypoints: https
      traefik.http.routers.freshrss.middlewares: auth-chain@file
      traefik.http.routers.freshrss.rule: Host(`${FRESHRSS_HOSTNAME:-freshrss}.${DOMAIN_NAME}`)
      traefik.http.routers.freshrss.service: freshrss
      traefik.http.services.freshrss.loadbalancer.server.port: 80
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
      
networks:
  traefik:
    external: true
