---
#
# docker-proxy - Proxy over your Docker socket
#
services:
  docker-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: docker-proxy
    networks:
      - docker_proxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read only
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

networks:
  docker_proxy:
    external: true
